import { CoverageReport, TelcoProvider } from '../types';

export const INITIAL_COVERAGE_REPORTS: CoverageReport[] = [
  // ==========================================
  // BATANGAS PROVINCE (Comprehensive Ground Coverage with Flat Barangay Code Foreign Keys)
  // ==========================================
  {
    id: 'cov-btg-port',
    barangay_code: 'btg_batangas_city_santa_clara',
    telco: 'Smart',
    barangay: 'Batangas Port & Passenger Terminal',
    city: 'Batangas City',
    province: 'Batangas',
    coordinates: [13.7565, 121.0435],
    signalRating: 5,
    networkType: '5G',
    speedMbps: 172.5,
    notes: 'Strong 5G across passenger terminal & fastcraft boarding gates. Signal drops inside cargo hold of steel RORO ships.',
    reporterName: 'BatangasPortScout',
    reportedAt: '2026-08-18T16:20:00Z',
    upvotes: 64
  },
  {
    id: 'cov-btg-port-globe',
    barangay_code: 'btg_batangas_city_santa_clara',
    telco: 'Globe',
    barangay: 'Batangas Port Access Rd (Brgy. Sta. Clara)',
    city: 'Batangas City',
    province: 'Batangas',
    coordinates: [13.7592, 121.0488],
    signalRating: 4,
    networkType: '4G/LTE',
    speedMbps: 48.0,
    notes: 'Steady LTE along port gates and truck staging area.',
    reporterName: 'PortTruckerPH',
    reportedAt: '2026-08-17T11:30:00Z',
    upvotes: 29
  },
  {
    id: 'cov-btg-bsu',
    barangay_code: 'btg_batangas_city_alangilan',
    telco: 'Smart',
    barangay: 'BatStateU Main Campus (Brgy. Alangilan)',
    city: 'Batangas City',
    province: 'Batangas',
    coordinates: [13.7844, 121.0743],
    signalRating: 5,
    networkType: '5G',
    speedMbps: 218.4,
    notes: 'Blazing Smart 5G around engineering building and university grounds. Ideal for research streaming.',
    reporterName: 'SpartanEngr',
    reportedAt: '2026-08-18T13:45:00Z',
    upvotes: 52
  },
  {
    id: 'cov-btg-bsu-dito',
    barangay_code: 'btg_batangas_city_alangilan',
    telco: 'DITO',
    barangay: 'Brgy. Alangilan (Grand Terminal Vicinity)',
    city: 'Batangas City',
    province: 'Batangas',
    coordinates: [13.7792, 121.0664],
    signalRating: 5,
    networkType: '5G',
    speedMbps: 146.0,
    notes: 'DITO 5G is super smooth across the Grand Terminal bus bays.',
    reporterName: 'BatangasCommuter',
    reportedAt: '2026-08-16T08:15:00Z',
    upvotes: 37
  },
  {
    id: 'cov-btg-capitol',
    barangay_code: 'btg_batangas_city_kumintang_ibaba',
    telco: 'Globe',
    barangay: 'Brgy. Kumintang Ibaba (Provincial Capitol)',
    city: 'Batangas City',
    province: 'Batangas',
    coordinates: [13.7588, 121.0583],
    signalRating: 5,
    networkType: '5G',
    speedMbps: 184.2,
    notes: 'Strong 5G along Capitol park, UB (University of Batangas), and Rizal Ave.',
    reporterName: 'AlaEhMakulit',
    reportedAt: '2026-08-18T14:10:00Z',
    upvotes: 41
  },
  {
    id: 'cov-btg-sm-lipa',
    barangay_code: 'btg_lipa_city_marauoy_marawoy',
    telco: 'Smart',
    barangay: 'SM City Lipa & Robinsons (Brgy. Marawoy)',
    city: 'Lipa City',
    province: 'Batangas',
    coordinates: [13.9427, 121.1631],
    signalRating: 5,
    networkType: '5G',
    speedMbps: 235.0,
    notes: 'Blazing 5G indoors and outdoors throughout Ayala Highway commercial corridor.',
    reporterName: 'LipeñoScout',
    reportedAt: '2026-08-18T18:00:00Z',
    upvotes: 78
  },
  {
    id: 'cov-btg-lima',
    barangay_code: 'btg_lipa_city_bugtong_na_pulo',
    telco: 'DITO',
    barangay: 'The Outlets at Lipa / LIMA Estate',
    city: 'Lipa City',
    province: 'Batangas',
    coordinates: [13.9934, 121.1568],
    signalRating: 5,
    networkType: '5G',
    speedMbps: 165.8,
    notes: 'Solid 5G speed across open-air shopping mall and Lima Technology Center.',
    reporterName: 'LimaShopper',
    reportedAt: '2026-08-17T15:20:00Z',
    upvotes: 45
  },
  {
    id: 'cov-btg-dlsl',
    barangay_code: 'btg_lipa_city_tambo',
    telco: 'Globe',
    barangay: 'De La Salle Lipa (Brgy. Tambo)',
    city: 'Lipa City',
    province: 'Batangas',
    coordinates: [13.9556, 121.1602],
    signalRating: 5,
    networkType: '5G',
    speedMbps: 192.3,
    notes: 'Excellent Globe 5G along JP Laurel Highway & DLSL gates.',
    reporterName: 'GreenLipeño',
    reportedAt: '2026-08-18T09:30:00Z',
    upvotes: 39
  },
  {
    id: 'cov-btg-fpip',
    barangay_code: 'btg_sto_tomas_city_santa_anastacia',
    telco: 'Smart',
    barangay: 'First Philippine Industrial Park (FPIP)',
    city: 'Sto. Tomas City',
    province: 'Batangas',
    coordinates: [14.1084, 121.1444],
    signalRating: 5,
    networkType: '5G',
    speedMbps: 242.0,
    notes: 'High-density industrial 5G coverage throughout FPIP Gates 1 and 2.',
    reporterName: 'IndustrialTechie',
    reportedAt: '2026-08-17T17:40:00Z',
    upvotes: 50
  },
  {
    id: 'cov-btg-tanauan',
    barangay_code: 'btg_tanauan_city_darasa',
    telco: 'Globe',
    barangay: 'Brgy. Darasa / Victory Mall',
    city: 'Tanauan City',
    province: 'Batangas',
    coordinates: [14.0862, 121.1523],
    signalRating: 4,
    networkType: '5G',
    speedMbps: 135.0,
    notes: 'Fast 5G around City Hall and public market.',
    reporterName: 'TanauanRider',
    reportedAt: '2026-08-15T12:00:00Z',
    upvotes: 32
  },
  {
    id: 'cov-btg-pico',
    barangay_code: 'btg_nasugbu_papaya',
    telco: 'Smart',
    barangay: 'Hamilo Coast & Pico de Loro (Brgy. Papaya)',
    city: 'Nasugbu',
    province: 'Batangas',
    coordinates: [14.1957, 120.5972],
    signalRating: 4,
    networkType: '4G/LTE',
    speedMbps: 58.2,
    notes: 'Steady Smart LTE along the beach club. Temporary deadzone inside the Kaybiang mountain tunnel.',
    reporterName: 'CoastExplorer',
    reportedAt: '2026-08-14T16:00:00Z',
    upvotes: 48
  },
  {
    id: 'cov-btg-nasugbu',
    barangay_code: 'btg_nasugbu_wawa',
    telco: 'Globe',
    barangay: 'Brgy. Wawa / Nasugbu Town Proper',
    city: 'Nasugbu',
    province: 'Batangas',
    coordinates: [14.0766, 120.6322],
    signalRating: 4,
    networkType: '4G/LTE',
    speedMbps: 42.5,
    notes: 'Reliable 4G across town plaza and beach resorts.',
    reporterName: 'BatangasBeachBum',
    reportedAt: '2026-08-13T10:20:00Z',
    upvotes: 27
  },
  {
    id: 'cov-btg-matabungkay',
    barangay_code: 'btg_lian_matabungkay',
    telco: 'Smart',
    barangay: 'Matabungkay Beach (Brgy. Matabungkay)',
    city: 'Lian',
    province: 'Batangas',
    coordinates: [13.9592, 120.6300],
    signalRating: 4,
    networkType: '4G/LTE',
    speedMbps: 45.0,
    notes: 'Good LTE signal for mobile gaming and social media on floating balsa.',
    reporterName: 'BalsaKing',
    reportedAt: '2026-08-12T14:40:00Z',
    upvotes: 33
  },
  {
    id: 'cov-btg-calatagan',
    barangay_code: 'btg_calatagan_bagong_silang',
    telco: 'Globe',
    barangay: 'Cape Santiago Lighthouse (Brgy. Bagong Silang)',
    city: 'Calatagan',
    province: 'Batangas',
    coordinates: [13.8166, 120.6558],
    signalRating: 3,
    networkType: '4G/LTE',
    speedMbps: 18.5,
    notes: 'Moderate LTE signal near the lighthouse. Intermittent drops along remote rocky coves.',
    reporterName: 'LighthouseChaser',
    reportedAt: '2026-08-11T16:15:00Z',
    upvotes: 24
  },
  {
    id: 'cov-btg-anilao',
    barangay_code: 'btg_mabini_solo',
    telco: 'Smart',
    barangay: 'Anilao Dive Resorts (Brgy. Solo & Ligaya)',
    city: 'Mabini',
    province: 'Batangas',
    coordinates: [13.7533, 120.8986],
    signalRating: 4,
    networkType: '4G/LTE',
    speedMbps: 54.0,
    notes: 'Strong outdoor 4G along dive spots and resort shores. Uploading macro underwater photos is snappy.',
    reporterName: 'AnilaoDiver',
    reportedAt: '2026-08-16T12:00:00Z',
    upvotes: 46
  },
  {
    id: 'cov-btg-gulugod',
    barangay_code: 'btg_mabini_ligaya',
    telco: 'Smart',
    barangay: 'Mt. Gulugod Baboy Summit',
    city: 'Mabini',
    province: 'Batangas',
    coordinates: [13.7431, 120.8936],
    signalRating: 5,
    networkType: '5G',
    speedMbps: 110.0,
    notes: 'Direct line-of-sight 5G on the mountain peak overlooking Balayan and Batangas Bay!',
    reporterName: 'HikerPH',
    reportedAt: '2026-08-15T07:30:00Z',
    upvotes: 59
  },
  {
    id: 'cov-btg-taal-heritage',
    barangay_code: 'btg_taal_poblacion_1',
    telco: 'Globe',
    barangay: 'Taal Basilica (Brgy. Poblacion)',
    city: 'Taal',
    province: 'Batangas',
    coordinates: [13.8804, 120.9238],
    signalRating: 4,
    networkType: '4G/LTE',
    speedMbps: 46.8,
    notes: 'Stable 4G along Spanish colonial ancestral street and heritage basilica.',
    reporterName: 'HeritageWalker',
    reportedAt: '2026-08-14T15:10:00Z',
    upvotes: 31
  },
  {
    id: 'cov-btg-maculot',
    barangay_code: 'btg_cuenca_barangay_1_poblacion',
    telco: 'Smart',
    barangay: 'Mt. Maculot Jump-off & Rockies',
    city: 'Cuenca',
    province: 'Batangas',
    coordinates: [13.9189, 121.0503],
    signalRating: 4,
    networkType: '4G/LTE',
    speedMbps: 36.0,
    notes: 'Good LTE at jump-off & campsite. Signal drops inside dense tree canopy along trail 7.',
    reporterName: 'MaculotTrekker',
    reportedAt: '2026-08-13T08:50:00Z',
    upvotes: 38
  },
  {
    id: 'cov-btg-star-km85',
    barangay_code: 'btg_san_jose_aguila',
    telco: 'DITO',
    barangay: 'STAR Tollway San Jose Cut (KM 85)',
    city: 'San Jose',
    province: 'Batangas',
    coordinates: [13.8833, 121.1167],
    signalRating: 4,
    networkType: '4G/LTE',
    speedMbps: 42.0,
    notes: 'Seamless LTE while driving through the STAR tollway highway stretch.',
    reporterName: 'ExpresswayDriver',
    reportedAt: '2026-08-17T09:40:00Z',
    upvotes: 25
  },

  // ==========================================
  // METRO MANILA & OTHER REGIONAL SEEDS
  // ==========================================
  {
    id: 'cov-mnl-1',
    telco: 'Smart',
    barangay: 'Brgy. San Lorenzo (Greenbelt / Glorietta)',
    city: 'Makati City',
    province: 'Metro Manila',
    coordinates: [14.5518, 121.0233],
    signalRating: 5,
    networkType: '5G',
    speedMbps: 215.4,
    notes: 'Ultra fast Smart 5G indoors and outdoors throughout Ayala Center.',
    reporterName: 'MakatiNomad',
    reportedAt: '2026-08-15T14:20:00Z',
    upvotes: 42
  },
  {
    id: 'cov-mnl-2',
    telco: 'Globe',
    barangay: 'Brgy. Fort Bonifacio (BGC High Street)',
    city: 'Taguig City',
    province: 'Metro Manila',
    coordinates: [14.5507, 121.0509],
    signalRating: 5,
    networkType: '5G',
    speedMbps: 188.6,
    notes: 'Flawless 5G coverage throughout 5th to 9th Avenue.',
    reporterName: 'BGC_Dev',
    reportedAt: '2026-08-16T11:45:00Z',
    upvotes: 38
  },
  {
    id: 'cov-mnl-3',
    telco: 'DITO',
    barangay: 'Brgy. Socorro (Cubao / Araneta City)',
    city: 'Quezon City',
    province: 'Metro Manila',
    coordinates: [14.6202, 121.0531],
    signalRating: 4,
    networkType: '5G',
    speedMbps: 142.0,
    notes: 'DITO 5G is super solid around Gateway Mall and MRT Station.',
    reporterName: 'QC_Rider',
    reportedAt: '2026-08-17T09:15:00Z',
    upvotes: 27
  },
  {
    id: 'cov-bgu-1',
    telco: 'Smart',
    barangay: 'Brgy. Session Road',
    city: 'Baguio City',
    province: 'Benguet',
    coordinates: [16.4124, 120.5980],
    signalRating: 5,
    networkType: '5G',
    speedMbps: 164.2,
    notes: 'Top tier 5G coverage along Session Road and Burnham Park.',
    reporterName: 'PineShooter',
    reportedAt: '2026-08-12T13:00:00Z',
    upvotes: 56
  },
  {
    id: 'cov-ceb-1',
    telco: 'Globe',
    barangay: 'Brgy. Cebu IT Park (Apas)',
    city: 'Cebu City',
    province: 'Cebu',
    coordinates: [10.3288, 123.9064],
    signalRating: 5,
    networkType: '5G',
    speedMbps: 205.8,
    notes: 'Dense 5G coverage throughout The Walk and Avida Towers.',
    reporterName: 'SugboTechie',
    reportedAt: '2026-08-17T15:40:00Z',
    upvotes: 49
  },
  {
    id: 'cov-dvo-1',
    telco: 'Smart',
    barangay: 'Brgy. Poblacion (Abreeza / Bajada)',
    city: 'Davao City',
    province: 'Davao del Sur',
    coordinates: [7.0917, 125.6128],
    signalRating: 5,
    networkType: '5G',
    speedMbps: 194.0,
    notes: 'Fast 5G signal along J.P. Laurel Avenue and Abreeza Ayala Mall.',
    reporterName: 'DurianExplorer',
    reportedAt: '2026-08-16T18:10:00Z',
    upvotes: 33
  }
];

export const TELCO_COLORS: Record<TelcoProvider, { primary: string; light: string; badge: string }> = {
  Globe: { primary: '#0055a5', light: '#e0edff', badge: '#1d72b8' },
  Smart: { primary: '#008a38', light: '#dcfce7', badge: '#16a34a' },
  DITO: { primary: '#dc2626', light: '#fee2e2', badge: '#ef4444' },
  GOMO: { primary: '#7c3aed', light: '#ede9fe', badge: '#8b5cf6' },
  TM: { primary: '#ea580c', light: '#ffedd5', badge: '#f97316' },
  TNT: { primary: '#d97706', light: '#fef3c7', badge: '#f59e0b' }
};
