import { PromoItem, TelcoProvider } from '../types';

/**
 * PHILIPPINE TELCO PROMO CATALOG (Point-in-time Snapshot)
 * --------------------------------------------------------
 * Last verified date: 2026-08-26
 * Sources: Official operator portals (store1.smart.com.ph, globe.com.ph,
 *          tntph.com, tmtambayan.ph, dito.ph, gomo.ph) and official mobile apps.
 *
 * NOTE: Philippine telco promos, pricing, quotas, and validity periods shift
 * frequently without prior notice. Since this dataset is an on-device point-in-time
 * snapshot without live scraping, it MUST be spot-checked and updated every 4-6 weeks
 * to ensure GCash load amounts and promo quotas remain strictly aligned with active telco offerings.
 *
 * Sourcing Confidence Tiers:
 * - 'high': Directly verified against live official telco web stores or app catalogs.
 * - 'medium': Account-targeted, "For You" deals, or transitional app-exclusive promos.
 */

export const DATASET_LAST_VERIFIED_DATE = '2026-08-26';

export const PHILIPPINE_PROMOS: PromoItem[] = [
  // ==========================================
  // --- SMART COMMUNICATIONS (store1.smart.com.ph) ---
  // ==========================================
  {
    id: 'smart-magic-data-99',
    telco: 'Smart',
    name: 'Magic Data 99',
    pricePhp: 99,
    dataAllowanceMb: 2 * 1024,
    validityDays: 0,
    isNoExpiry: true,
    freebieDetails: '2GB Pure Open Access Data with No Expiration',
    inclusions: 'Non-Expiring Data',
    ussdCode: '*123#',
    smsKeyword: 'MAGIC99',
    smsSendTo: '9999',
    category: 'no_expiry',
    highlights: ['No Expiration', 'Zero Waste Backup', '₱49.50 / GB'],
    costPerGb: 49.50,
    lastVerifiedDate: '2026-08-26',
    confidence: 'high'
  },
  {
    id: 'smart-magic-data-149',
    telco: 'Smart',
    name: 'Magic Data 149',
    pricePhp: 149,
    dataAllowanceMb: 3 * 1024,
    validityDays: 0,
    isNoExpiry: true,
    freebieDetails: '3GB Pure Open Access Data with No Expiration',
    inclusions: 'Non-Expiring Data',
    ussdCode: '*123#',
    smsKeyword: 'MAGIC149',
    smsSendTo: '9999',
    category: 'no_expiry',
    highlights: ['Never Expires', '3GB Pure Data', '₱49.67 / GB'],
    costPerGb: 49.67,
    lastVerifiedDate: '2026-08-26',
    confidence: 'high'
  },
  {
    id: 'smart-magic-data-249',
    telco: 'Smart',
    name: 'Magic Data 249',
    pricePhp: 249,
    dataAllowanceMb: 8 * 1024,
    validityDays: 0,
    isNoExpiry: true,
    freebieDetails: '8GB Pure Open Access Data with No Expiration',
    inclusions: 'Non-Expiring Data',
    ussdCode: '*123#',
    smsKeyword: 'MAGIC249',
    smsSendTo: '9999',
    category: 'no_expiry',
    highlights: ['Never Expires', '8GB Pure Data', '₱31.13 / GB'],
    costPerGb: 31.13,
    lastVerifiedDate: '2026-08-26',
    confidence: 'high'
  },
  {
    id: 'smart-magic-data-349',
    telco: 'Smart',
    name: 'Magic Data 349',
    pricePhp: 349,
    dataAllowanceMb: 16 * 1024,
    validityDays: 0,
    isNoExpiry: true,
    freebieDetails: '16GB Pure Open Access Data with No Expiration',
    inclusions: 'Non-Expiring Data',
    ussdCode: '*123#',
    smsKeyword: 'MAGIC349',
    smsSendTo: '9999',
    category: 'no_expiry',
    highlights: ['Best Seller No-Expiry', '16GB Data', '₱21.81 / GB'],
    costPerGb: 21.81,
    lastVerifiedDate: '2026-08-26',
    confidence: 'high'
  },
  {
    id: 'smart-magic-data-449',
    telco: 'Smart',
    name: 'Magic Data 449',
    pricePhp: 449,
    dataAllowanceMb: 26 * 1024,
    validityDays: 0,
    isNoExpiry: true,
    freebieDetails: '26GB Pure Open Access Data with No Expiration',
    inclusions: 'Non-Expiring Data',
    ussdCode: '*123#',
    smsKeyword: 'MAGIC449',
    smsSendTo: '9999',
    category: 'no_expiry',
    highlights: ['Heavy No-Expiry', '26GB Data', '₱17.27 / GB'],
    costPerGb: 17.27,
    lastVerifiedDate: '2026-08-26',
    confidence: 'high'
  },
  {
    id: 'smart-magic-data-549',
    telco: 'Smart',
    name: 'Magic Data 549',
    pricePhp: 549,
    dataAllowanceMb: 38 * 1024,
    validityDays: 0,
    isNoExpiry: true,
    freebieDetails: '38GB Pure Open Access Data with No Expiration',
    inclusions: 'Non-Expiring Data',
    ussdCode: '*123#',
    smsKeyword: 'MAGIC549',
    smsSendTo: '9999',
    category: 'no_expiry',
    highlights: ['High Volume Data', '38GB Data', '₱14.45 / GB'],
    costPerGb: 14.45,
    lastVerifiedDate: '2026-08-26',
    confidence: 'high'
  },
  {
    id: 'smart-magic-data-649',
    telco: 'Smart',
    name: 'Magic Data 649',
    pricePhp: 649,
    dataAllowanceMb: 50 * 1024,
    validityDays: 0,
    isNoExpiry: true,
    freebieDetails: '50GB Pure Open Access Data with No Expiration',
    inclusions: 'Non-Expiring Data',
    ussdCode: '*123#',
    smsKeyword: 'MAGIC649',
    smsSendTo: '9999',
    category: 'no_expiry',
    highlights: ['Ultra Bulk No-Expiry', '50GB Data', '₱12.98 / GB'],
    costPerGb: 12.98,
    lastVerifiedDate: '2026-08-26',
    confidence: 'high'
  },
  {
    id: 'smart-magic-data-749',
    telco: 'Smart',
    name: 'Magic Data 749',
    pricePhp: 749,
    dataAllowanceMb: 65 * 1024,
    validityDays: 0,
    isNoExpiry: true,
    freebieDetails: '65GB Pure Open Access Data with No Expiration',
    inclusions: 'Non-Expiring Data',
    ussdCode: '*123#',
    smsKeyword: 'MAGIC749',
    smsSendTo: '9999',
    category: 'no_expiry',
    highlights: ['Max No-Expiry Pack', '65GB Data', '₱11.52 / GB'],
    costPerGb: 11.52,
    lastVerifiedDate: '2026-08-26',
    confidence: 'high'
  },
  {
    id: 'smart-magic-data-plus-199',
    telco: 'Smart',
    name: 'Magic Data+ 199',
    pricePhp: 199,
    dataAllowanceMb: 4 * 1024,
    validityDays: 0,
    isNoExpiry: true,
    freebieDetails: '4GB Data + 50 mins All-Net Calls + 50 All-Net SMS (No Expiry)',
    inclusions: '50 mins calls + 50 SMS',
    ussdCode: '*123#',
    smsKeyword: 'MAGICPLUS199',
    smsSendTo: '9999',
    category: 'no_expiry',
    highlights: ['Calls/SMS Included', 'No Expiration', '₱49.75 / GB'],
    costPerGb: 49.75,
    lastVerifiedDate: '2026-08-26',
    confidence: 'high'
  },
  {
    id: 'smart-magic-data-plus-399',
    telco: 'Smart',
    name: 'Magic Data+ 399',
    pricePhp: 399,
    dataAllowanceMb: 10 * 1024,
    validityDays: 0,
    isNoExpiry: true,
    freebieDetails: '10GB Data + 100 mins All-Net Calls + 100 All-Net SMS (No Expiry)',
    inclusions: '100 mins calls + 100 SMS',
    ussdCode: '*123#',
    smsKeyword: 'MAGICPLUS399',
    smsSendTo: '9999',
    category: 'no_expiry',
    highlights: ['10GB + 100 mins/SMS', 'Never Expires', '₱39.90 / GB'],
    costPerGb: 39.90,
    lastVerifiedDate: '2026-08-26',
    confidence: 'high'
  },
  {
    id: 'smart-magic-data-plus-649',
    telco: 'Smart',
    name: 'Magic Data+ 649',
    pricePhp: 649,
    dataAllowanceMb: 30 * 1024,
    validityDays: 0,
    isNoExpiry: true,
    freebieDetails: '30GB Data + 200 mins All-Net Calls + 200 All-Net SMS (No Expiry)',
    inclusions: '200 mins calls + 200 SMS',
    ussdCode: '*123#',
    smsKeyword: 'MAGICPLUS649',
    smsSendTo: '9999',
    category: 'no_expiry',
    highlights: ['30GB + 200 mins/SMS', 'Never Expires', '₱21.63 / GB'],
    costPerGb: 21.63,
    lastVerifiedDate: '2026-08-26',
    confidence: 'high'
  },
  {
    id: 'smart-power-all-99',
    telco: 'Smart',
    name: 'Power All 99',
    pricePhp: 99,
    dataAllowanceMb: 8 * 1024,
    validityDays: 7,
    isNoExpiry: false,
    freebieDetails: '8GB All-Access Data + Unli TikTok + Unli All-Net Calls/SMS',
    inclusions: 'Unli TikTok + Unli Calls/SMS',
    ussdCode: '*123#',
    smsKeyword: 'POWER99',
    smsSendTo: '9999',
    category: 'popular',
    highlights: ['Unli TikTok Daily', 'Unli Allnet Calls/SMS', '₱12.38 / GB'],
    costPerGb: 12.38,
    lastVerifiedDate: '2026-08-26',
    confidence: 'high'
  },
  {
    id: 'smart-power-all-149',
    telco: 'Smart',
    name: 'Power All 149',
    pricePhp: 149,
    dataAllowanceMb: 12 * 1024,
    validityDays: 7,
    isNoExpiry: false,
    freebieDetails: '12GB All-Access Data + Unli TikTok + Unli All-Net Calls/SMS',
    inclusions: 'Unli TikTok + Unli Calls/SMS',
    ussdCode: '*123#',
    smsKeyword: 'POWER149',
    smsSendTo: '9999',
    category: 'heavy_data',
    highlights: ['12GB Open Access', 'Unli TikTok', '₱12.42 / GB'],
    costPerGb: 12.42,
    lastVerifiedDate: '2026-08-26',
    confidence: 'high'
  },
  {
    id: 'smart-all-data-50',
    telco: 'Smart',
    name: 'All Data 50',
    pricePhp: 50,
    dataAllowanceMb: 5 * 1024,
    validityDays: 3,
    isNoExpiry: false,
    freebieDetails: '5GB Pure Open-Access Data for all sites & apps',
    inclusions: '5GB All Access',
    ussdCode: '*123#',
    smsKeyword: 'ALLDATA50',
    smsSendTo: '9999',
    category: 'budget',
    highlights: ['Short Trip Hero', '5GB Pure Data', '₱10.00 / GB'],
    costPerGb: 10.00,
    lastVerifiedDate: '2026-08-26',
    confidence: 'high'
  },
  {
    id: 'smart-all-data-99',
    telco: 'Smart',
    name: 'All Data 99',
    pricePhp: 99,
    dataAllowanceMb: 9 * 1024,
    validityDays: 7,
    isNoExpiry: false,
    freebieDetails: '9GB Pure Open-Access Data for all sites & apps',
    inclusions: '9GB All Access',
    ussdCode: '*123#',
    smsKeyword: 'ALLDATA99',
    smsSendTo: '9999',
    category: 'popular',
    highlights: ['Weekly Staple', '9GB Pure Data', '₱11.00 / GB'],
    costPerGb: 11.00,
    lastVerifiedDate: '2026-08-26',
    confidence: 'high'
  },
  {
    id: 'smart-all-data-299',
    telco: 'Smart',
    name: 'All Data 299',
    pricePhp: 299,
    dataAllowanceMb: 24 * 1024,
    validityDays: 30,
    isNoExpiry: false,
    freebieDetails: '24GB Open-Access Data valid for 30 days',
    inclusions: '24GB 30-Day Data',
    ussdCode: '*123#',
    smsKeyword: 'ALLDATA299',
    smsSendTo: '9999',
    category: 'heavy_data',
    highlights: ['30 Days Peace of Mind', '24GB Data', '₱12.46 / GB'],
    costPerGb: 12.46,
    lastVerifiedDate: '2026-08-26',
    confidence: 'high'
  },
  {
    id: 'smart-all-data-399',
    telco: 'Smart',
    name: 'All Data 399',
    pricePhp: 399,
    dataAllowanceMb: 36 * 1024,
    validityDays: 30,
    isNoExpiry: false,
    freebieDetails: '36GB Open-Access Data valid for 30 days',
    inclusions: '36GB 30-Day Data',
    ussdCode: '*123#',
    smsKeyword: 'ALLDATA399',
    smsSendTo: '9999',
    category: 'heavy_data',
    highlights: ['Monthly Heavy Duty', '36GB Data', '₱11.08 / GB'],
    costPerGb: 11.08,
    lastVerifiedDate: '2026-08-26',
    confidence: 'high'
  },
  {
    id: 'smart-all-data-499',
    telco: 'Smart',
    name: 'All Data 499',
    pricePhp: 499,
    dataAllowanceMb: 50 * 1024,
    validityDays: 30,
    isNoExpiry: false,
    freebieDetails: '50GB Open-Access Data valid for 30 days',
    inclusions: '50GB 30-Day Data',
    ussdCode: '*123#',
    smsKeyword: 'ALLDATA499',
    smsSendTo: '9999',
    category: 'heavy_data',
    highlights: ['Pro Monthly User', '50GB Data', '₱9.98 / GB'],
    costPerGb: 9.98,
    lastVerifiedDate: '2026-08-26',
    confidence: 'high'
  },
  {
    id: 'smart-all-data-599',
    telco: 'Smart',
    name: 'All Data 599',
    pricePhp: 599,
    dataAllowanceMb: 65 * 1024,
    validityDays: 30,
    isNoExpiry: false,
    freebieDetails: '65GB Open-Access Data valid for 30 days',
    inclusions: '65GB 30-Day Data',
    ussdCode: '*123#',
    smsKeyword: 'ALLDATA599',
    smsSendTo: '9999',
    category: 'heavy_data',
    highlights: ['Max Allowance Monthly', '65GB Data', '₱9.22 / GB'],
    costPerGb: 9.22,
    lastVerifiedDate: '2026-08-26',
    confidence: 'high'
  },
  {
    id: 'smart-unli-data-399',
    telco: 'Smart',
    name: 'Unli Data 399',
    pricePhp: 399,
    dataAllowanceMb: 999 * 1024,
    validityDays: 30,
    isNoExpiry: false,
    freebieDetails: 'Unlimited Data for 30 Days (Smart App / *123# Account Targeted)',
    inclusions: 'Unli All-Access Data',
    ussdCode: '*123#',
    category: 'unli',
    highlights: ['Unlimited High Speed', '30 Days Validity', '< ₱0.40 / GB'],
    costPerGb: 0.40,
    lastVerifiedDate: '2026-08-26',
    confidence: 'medium'
  },
  {
    id: 'smart-unli-data-999',
    telco: 'Smart',
    name: 'Unli Data 999',
    pricePhp: 999,
    dataAllowanceMb: 999 * 1024,
    validityDays: 30,
    isNoExpiry: false,
    freebieDetails: 'True Unlimited Data for 30 Days on Smart Bro / Home WiFi / 5G',
    inclusions: 'Unli 30 Days',
    ussdCode: '*123#',
    smsKeyword: 'UNLI999',
    smsSendTo: '9999',
    category: 'unli',
    highlights: ['Guaranteed Unlimited', 'Bro & Mobile', '₱1.00 / GB equivalent'],
    costPerGb: 1.00,
    lastVerifiedDate: '2026-08-26',
    confidence: 'high'
  },
  {
    id: 'smart-unli-5g-299',
    telco: 'Smart',
    name: 'Unli 5G 299',
    pricePhp: 299,
    dataAllowanceMb: 999 * 1024,
    validityDays: 7,
    isNoExpiry: false,
    freebieDetails: 'Unlimited 5G Data + 10GB Non-5G Data for 7 days',
    inclusions: 'Unli 5G + 10GB 4G',
    ussdCode: '*123#',
    category: 'unli',
    highlights: ['Ultra-Fast 5G Unli', '10GB 4G Backup', '< ₱0.30 / GB'],
    costPerGb: 0.30,
    lastVerifiedDate: '2026-08-26',
    confidence: 'high'
  },
  {
    id: 'smart-giga-video-99',
    telco: 'Smart',
    name: 'GIGA Video 99',
    pricePhp: 99,
    dataAllowanceMb: 9 * 1024,
    validityDays: 7,
    isNoExpiry: false,
    freebieDetails: '2GB Open Data + 1GB/day YouTube, Netflix, Prime Video (7 Days)',
    inclusions: '1GB/day Video Apps',
    ussdCode: '*123#',
    smsKeyword: 'GIGA99',
    smsSendTo: '9999',
    category: 'popular',
    highlights: ['Daily Streaming Data', '9GB Total', '₱11.00 / GB'],
    costPerGb: 11.00,
    lastVerifiedDate: '2026-08-26',
    confidence: 'high'
  },

  // ==========================================
  // --- GLOBE TELECOM (globe.com.ph/prepaid) ---
  // ==========================================
  {
    id: 'globe-go-50',
    telco: 'Globe',
    name: 'Go50',
    pricePhp: 50,
    dataAllowanceMb: 5 * 1024,
    validityDays: 3,
    isNoExpiry: false,
    freebieDetails: '5GB All-Access Data + 1GB GoWiFi + Unli All-Net SMS',
    inclusions: 'Unli Allnet SMS + 1GB GoWiFi',
    ussdCode: '*143#',
    smsKeyword: 'GO50',
    smsSendTo: '8080',
    category: 'budget',
    highlights: ['Short Trip Hero', '5GB All-Access', '₱10.00 / GB'],
    costPerGb: 10.00,
    lastVerifiedDate: '2026-08-26',
    confidence: 'high'
  },
  {
    id: 'globe-go-90',
    telco: 'Globe',
    name: 'Go90',
    pricePhp: 90,
    dataAllowanceMb: 8 * 1024,
    validityDays: 7,
    isNoExpiry: false,
    freebieDetails: '8GB All-Access Data + 1GB GoWiFi + Unli All-Net SMS',
    inclusions: 'Unli Allnet SMS + 1GB GoWiFi',
    ussdCode: '*143#',
    smsKeyword: 'GO90',
    smsSendTo: '8080',
    category: 'budget',
    highlights: ['Weekly Staple', '8GB Open Access', '₱11.25 / GB'],
    costPerGb: 11.25,
    lastVerifiedDate: '2026-08-26',
    confidence: 'high'
  },
  {
    id: 'globe-go-120',
    telco: 'Globe',
    name: 'Go120',
    pricePhp: 120,
    dataAllowanceMb: 10 * 1024,
    validityDays: 7,
    isNoExpiry: false,
    freebieDetails: '10GB All-Access Data + Unli All-Net SMS + Unli Globe/TM Calls',
    inclusions: 'Unli SMS + Unli Globe/TM Calls',
    ussdCode: '*143#',
    smsKeyword: 'GO120',
    smsSendTo: '8080',
    category: 'popular',
    highlights: ['10GB Data', 'Unli Globe/TM Calls', '₱12.00 / GB'],
    costPerGb: 12.00,
    lastVerifiedDate: '2026-08-26',
    confidence: 'high'
  },
  {
    id: 'globe-go-140',
    telco: 'Globe',
    name: 'Go140',
    pricePhp: 140,
    dataAllowanceMb: 11 * 1024,
    validityDays: 7,
    isNoExpiry: false,
    freebieDetails: '11GB All-Access Data + Unli All-Net SMS + Unli All-Net Calls',
    inclusions: 'Unli Allnet Calls & SMS',
    ussdCode: '*143#',
    smsKeyword: 'GO140',
    smsSendTo: '8080',
    category: 'popular',
    highlights: ['11GB Open Access', 'Unli Allnet Calls', '₱12.73 / GB'],
    costPerGb: 12.73,
    lastVerifiedDate: '2026-08-26',
    confidence: 'high'
  },
  {
    id: 'globe-goextra-99',
    telco: 'Globe',
    name: 'GoEXTRA99',
    pricePhp: 99,
    dataAllowanceMb: 12 * 1024,
    validityDays: 7,
    isNoExpiry: false,
    freebieDetails: '8GB Open Data + 4GB Free 5G + Unli All-Net Calls & SMS',
    inclusions: 'Unli Allnet Calls/SMS + 4GB 5G',
    ussdCode: '*143#',
    smsKeyword: 'GOEXTRA99',
    smsSendTo: '8080',
    category: 'popular',
    highlights: ['Best Seller', 'Unli Allnet Calls/SMS', '₱8.25 / GB'],
    costPerGb: 8.25,
    lastVerifiedDate: '2026-08-26',
    confidence: 'high'
  },
  {
    id: 'globe-goextra-199',
    telco: 'Globe',
    name: 'GoEXTRA199',
    pricePhp: 199,
    dataAllowanceMb: 20 * 1024,
    validityDays: 15,
    isNoExpiry: false,
    freebieDetails: '15GB Open Data + 5GB Free 5G + Unli All-Net Calls & SMS for 15 Days',
    inclusions: 'Unli Calls/SMS + 5GB 5G',
    ussdCode: '*143#',
    smsKeyword: 'GOEXTRA199',
    smsSendTo: '8080',
    category: 'heavy_data',
    highlights: ['15-Day Long Stay', '20GB Total Data', '₱9.95 / GB'],
    costPerGb: 9.95,
    lastVerifiedDate: '2026-08-26',
    confidence: 'high'
  },
  {
    id: 'globe-go-plus-99',
    telco: 'Globe',
    name: 'Go+99',
    pricePhp: 99,
    dataAllowanceMb: 20 * 1024,
    validityDays: 7,
    isNoExpiry: false,
    freebieDetails: '8GB Open + 8GB Choice Apps (GoWATCH/GoWORK) + 4GB 5G + Unli SMS',
    inclusions: '8GB App Choice + Unli SMS',
    ussdCode: '*143#',
    smsKeyword: 'GOPLUS99',
    smsSendTo: '8080',
    category: 'heavy_data',
    highlights: ['20GB Total Data', 'App Booster Choice', '₱4.95 / GB'],
    costPerGb: 4.95,
    lastVerifiedDate: '2026-08-26',
    confidence: 'high'
  },
  {
    id: 'globe-go-plus-129',
    telco: 'Globe',
    name: 'Go+129',
    pricePhp: 129,
    dataAllowanceMb: 18 * 1024,
    validityDays: 7,
    isNoExpiry: false,
    freebieDetails: '10GB Open Data + 8GB Choice Apps + Unli All-Net Calls & SMS',
    inclusions: '8GB App Choice + Unli Calls/SMS',
    ussdCode: '*143#',
    smsKeyword: 'GOPLUS129',
    smsSendTo: '8080',
    category: 'heavy_data',
    highlights: ['18GB Data', 'Unli Allnet Calls', '₱7.17 / GB'],
    costPerGb: 7.17,
    lastVerifiedDate: '2026-08-26',
    confidence: 'high'
  },
  {
    id: 'globe-go-plus-149',
    telco: 'Globe',
    name: 'Go+149',
    pricePhp: 149,
    dataAllowanceMb: 20 * 1024,
    validityDays: 7,
    isNoExpiry: false,
    freebieDetails: '12GB Open + 8GB Choice Apps + Unlimited 5G + Unli All-Net SMS',
    inclusions: 'Unli 5G + 8GB Apps + Unli SMS',
    ussdCode: '*143#',
    smsKeyword: 'GOPLUS149',
    smsSendTo: '8080',
    category: 'heavy_data',
    highlights: ['Unlimited 5G Data', '20GB Total Base', '₱7.45 / GB'],
    costPerGb: 7.45,
    lastVerifiedDate: '2026-08-26',
    confidence: 'high'
  },
  {
    id: 'globe-go-plus-250',
    telco: 'Globe',
    name: 'Go+250',
    pricePhp: 250,
    dataAllowanceMb: 30 * 1024,
    validityDays: 15,
    isNoExpiry: false,
    freebieDetails: '15GB Open + 15GB Choice Apps + Unli All-Net SMS for 15 Days',
    inclusions: '15GB App Choice + Unli SMS',
    ussdCode: '*143#',
    smsKeyword: 'GOPLUS250',
    smsSendTo: '8080',
    category: 'heavy_data',
    highlights: ['30GB Total', '15 Days Validity', '₱8.33 / GB'],
    costPerGb: 8.33,
    lastVerifiedDate: '2026-08-26',
    confidence: 'high'
  },
  {
    id: 'globe-go-plus-400',
    telco: 'Globe',
    name: 'Go+400',
    pricePhp: 400,
    dataAllowanceMb: 40 * 1024,
    validityDays: 15,
    isNoExpiry: false,
    freebieDetails: '25GB Open + 15GB Choice Apps + Unli All-Net Calls/SMS for 15 Days',
    inclusions: '15GB Apps + Unli Calls/SMS',
    ussdCode: '*143#',
    smsKeyword: 'GOPLUS400',
    smsSendTo: '8080',
    category: 'heavy_data',
    highlights: ['40GB Big Data', 'Unli Allnet Calls', '₱10.00 / GB'],
    costPerGb: 10.00,
    lastVerifiedDate: '2026-08-26',
    confidence: 'high'
  },
  {
    id: 'globe-supergo-99',
    telco: 'Globe',
    name: 'SuperGo 99',
    pricePhp: 99,
    dataAllowanceMb: 10 * 1024,
    validityDays: 7,
    isNoExpiry: false,
    freebieDetails: '10GB All-Access Data + Unli All-Net SMS (GlobeOne App Exclusive)',
    inclusions: 'Unli Allnet SMS',
    ussdCode: '*143#',
    category: 'popular',
    highlights: ['10GB Open Data', 'GlobeOne Special', '₱9.90 / GB'],
    costPerGb: 9.90,
    lastVerifiedDate: '2026-08-26',
    confidence: 'medium'
  },
  {
    id: 'globe-supergo-149',
    telco: 'Globe',
    name: 'SuperGo 149',
    pricePhp: 149,
    dataAllowanceMb: 15 * 1024,
    validityDays: 7,
    isNoExpiry: false,
    freebieDetails: '15GB All-Access Data + Unli Calls & SMS to all networks',
    inclusions: 'Unli Allnet Calls/SMS',
    ussdCode: '*143#',
    category: 'heavy_data',
    highlights: ['Heavy Gaming/Video', 'Unli Allnet', '₱9.93 / GB'],
    costPerGb: 9.93,
    lastVerifiedDate: '2026-08-26',
    confidence: 'medium'
  },
  {
    id: 'globe-surf4all-99',
    telco: 'Globe',
    name: 'SURF4ALL99',
    pricePhp: 99,
    dataAllowanceMb: 9 * 1024,
    validityDays: 7,
    isNoExpiry: false,
    freebieDetails: '9GB Shareable Data with up to 4 users/SIMs simultaneously',
    inclusions: 'Group Shareable Data (4 SIMs)',
    ussdCode: '*143#',
    smsKeyword: 'SURF4ALL99',
    smsSendTo: '8080',
    category: 'popular',
    highlights: ['Family/Group Share', 'Multi-device pool', '₱11.00 / GB'],
    costPerGb: 11.00,
    lastVerifiedDate: '2026-08-26',
    confidence: 'high'
  },
  {
    id: 'globe-surf4all-249',
    telco: 'Globe',
    name: 'SURF4ALL249',
    pricePhp: 249,
    dataAllowanceMb: 20 * 1024,
    validityDays: 7,
    isNoExpiry: false,
    freebieDetails: '20GB Shareable Data with up to 4 users/SIMs simultaneously',
    inclusions: 'Group Shareable Data (4 SIMs)',
    ussdCode: '*143#',
    smsKeyword: 'SURF4ALL249',
    smsSendTo: '8080',
    category: 'heavy_data',
    highlights: ['20GB Family Pool', '4 Devices Max', '₱12.45 / GB'],
    costPerGb: 12.45,
    lastVerifiedDate: '2026-08-26',
    confidence: 'high'
  },
  {
    id: 'globe-gounli-95',
    telco: 'Globe',
    name: 'GoUNLI95',
    pricePhp: 95,
    dataAllowanceMb: 2560,
    validityDays: 7,
    isNoExpiry: false,
    freebieDetails: 'Unli Calls to Globe/TM + Unli All-Net SMS + 2.5GB Data',
    inclusions: 'Unli Globe/TM Calls + Unli SMS',
    ussdCode: '*143#',
    smsKeyword: 'GOUNLI95',
    smsSendTo: '8080',
    category: 'popular',
    highlights: ['Unli Calls to Globe/TM', 'Unli Allnet SMS', '₱38.00 / GB'],
    costPerGb: 38.00,
    lastVerifiedDate: '2026-08-26',
    confidence: 'high'
  },
  {
    id: 'globe-gounli-180',
    telco: 'Globe',
    name: 'GoUNLI180',
    pricePhp: 180,
    dataAllowanceMb: 5 * 1024,
    validityDays: 15,
    isNoExpiry: false,
    freebieDetails: 'Unli Calls to Globe/TM + Unli All-Net SMS + 5GB Data for 15 Days',
    inclusions: 'Unli Globe/TM Calls + Unli SMS',
    ussdCode: '*143#',
    smsKeyword: 'GOUNLI180',
    smsSendTo: '8080',
    category: 'popular',
    highlights: ['15-Day Unli Calls', '5GB Data', '₱36.00 / GB'],
    costPerGb: 36.00,
    lastVerifiedDate: '2026-08-26',
    confidence: 'high'
  },
  {
    id: 'globe-gounli-350',
    telco: 'Globe',
    name: 'GoUNLI350',
    pricePhp: 350,
    dataAllowanceMb: 10 * 1024,
    validityDays: 30,
    isNoExpiry: false,
    freebieDetails: 'Unli Calls to Globe/TM + Unli All-Net SMS + 10GB Data for 30 Days',
    inclusions: 'Unli Globe/TM Calls + Unli SMS',
    ussdCode: '*143#',
    smsKeyword: 'GOUNLI350',
    smsSendTo: '8080',
    category: 'popular',
    highlights: ['30-Day Unli Calls', '10GB Data', '₱35.00 / GB'],
    costPerGb: 35.00,
    lastVerifiedDate: '2026-08-26',
    confidence: 'high'
  },
  {
    id: 'globe-unli-5g-299',
    telco: 'Globe',
    name: 'Globe Unli 5G 299',
    pricePhp: 299,
    dataAllowanceMb: 999 * 1024,
    validityDays: 7,
    isNoExpiry: false,
    freebieDetails: 'Unlimited 5G Data + 10GB Regular 4G Data for 7 days',
    inclusions: 'Unli 5G + 10GB 4G Data',
    ussdCode: '*143#',
    category: 'unli',
    highlights: ['Unli 5G Data', '10GB Non-5G Backup', '< ₱0.30 / GB'],
    costPerGb: 0.30,
    lastVerifiedDate: '2026-08-26',
    confidence: 'high'
  },

  // ==========================================
  // --- TNT (tntph.com/pages/surfsaya) ---
  // ==========================================
  {
    id: 'tnt-surfsaya-20',
    telco: 'TNT',
    name: 'SurfSaya 20',
    pricePhp: 20,
    dataAllowanceMb: 500,
    validityDays: 2,
    isNoExpiry: false,
    freebieDetails: '300MB Open + 150MB/day FB/ML/TikTok + Unli All-Net Calls/SMS (2 Days)',
    inclusions: 'Unli Allnet Calls/SMS + Passion Data',
    ussdCode: '*123#',
    smsKeyword: 'SURFSAYA20',
    smsSendTo: '4545',
    category: 'budget',
    highlights: ['Only ₱20', 'Unli Calls & Texts', '₱40.00 / GB'],
    costPerGb: 40.00,
    lastVerifiedDate: '2026-08-26',
    confidence: 'high'
  },
  {
    id: 'tnt-surfsaya-30',
    telco: 'TNT',
    name: 'SurfSaya 30',
    pricePhp: 30,
    dataAllowanceMb: 1200,
    validityDays: 3,
    isNoExpiry: false,
    freebieDetails: '450MB Open + 250MB/day FB/ML/TikTok + Unli All-Net Calls & Texts (3 Days)',
    inclusions: 'Unli Allnet Calls/SMS + Passion Data',
    ussdCode: '*123#',
    smsKeyword: 'SURFSAYA30',
    smsSendTo: '4545',
    category: 'budget',
    highlights: ['Budget Favorite', '1.2GB Total Data', '₱25.00 / GB'],
    costPerGb: 25.00,
    lastVerifiedDate: '2026-08-26',
    confidence: 'high'
  },
  {
    id: 'tnt-surfsaya-49',
    telco: 'TNT',
    name: 'SurfSaya 49',
    pricePhp: 49,
    dataAllowanceMb: 1200,
    validityDays: 7,
    isNoExpiry: false,
    freebieDetails: '500MB Open + 100MB/day FB/ML/TikTok + Unli All-Net Calls & Texts (7 Days)',
    inclusions: 'Unli Allnet Calls/SMS + Passion Data',
    ussdCode: '*123#',
    smsKeyword: 'SURFSAYA49',
    smsSendTo: '4545',
    category: 'budget',
    highlights: ['7-Day Budget Staple', 'Unli Calls & SMS', '₱40.83 / GB'],
    costPerGb: 40.83,
    lastVerifiedDate: '2026-08-26',
    confidence: 'high'
  },
  {
    id: 'tnt-surfsaya-99',
    telco: 'TNT',
    name: 'SurfSaya 99',
    pricePhp: 99,
    dataAllowanceMb: 2200,
    validityDays: 7,
    isNoExpiry: false,
    freebieDetails: '1.5GB Open + 100MB/day FB/ML/TikTok + Unli All-Net Calls & Texts (7 Days)',
    inclusions: 'Unli Allnet Calls/SMS + Passion Data',
    ussdCode: '*123#',
    smsKeyword: 'SURFSAYA99',
    smsSendTo: '4545',
    category: 'popular',
    highlights: ['2.2GB Total', 'Unli Allnet Calls & SMS', '₱45.00 / GB'],
    costPerGb: 45.00,
    lastVerifiedDate: '2026-08-26',
    confidence: 'high'
  },
  {
    id: 'tnt-surfsaya-199',
    telco: 'TNT',
    name: 'SurfSaya 199',
    pricePhp: 199,
    dataAllowanceMb: 8 * 1024,
    validityDays: 30,
    isNoExpiry: false,
    freebieDetails: '2GB Open + 200MB/day FB/ML/TikTok + Unli All-Net Calls/SMS for 30 Days',
    inclusions: '30 Days Unli Calls/SMS + Passion Data',
    ussdCode: '*123#',
    smsKeyword: 'SURFSAYA199',
    smsSendTo: '4545',
    category: 'heavy_data',
    highlights: ['30 Days Validity', '8GB Total Data', '₱24.30 / GB'],
    costPerGb: 24.30,
    lastVerifiedDate: '2026-08-26',
    confidence: 'high'
  },
  {
    id: 'tnt-panalo-data-10',
    telco: 'TNT',
    name: 'Panalo Data 10',
    pricePhp: 10,
    dataAllowanceMb: 1024,
    validityDays: 1,
    isNoExpiry: false,
    freebieDetails: '1GB Pure Open Access Data for 1 Day',
    inclusions: '1GB 1-Day Data',
    ussdCode: '*123#',
    smsKeyword: 'PANALO10',
    smsSendTo: '4545',
    category: 'budget',
    highlights: ['Only ₱10', '1GB Full Speed', '₱10.00 / GB'],
    costPerGb: 10.00,
    lastVerifiedDate: '2026-08-26',
    confidence: 'high'
  },
  {
    id: 'tnt-panalo-data-30',
    telco: 'TNT',
    name: 'Panalo Data 30',
    pricePhp: 30,
    dataAllowanceMb: 3 * 1024,
    validityDays: 3,
    isNoExpiry: false,
    freebieDetails: '3GB Pure Open Access Data for 3 Days',
    inclusions: '3GB 3-Day Data',
    ussdCode: '*123#',
    smsKeyword: 'PANALO30',
    smsSendTo: '4545',
    category: 'budget',
    highlights: ['3GB for ₱30', '3 Days Open Data', '₱10.00 / GB'],
    costPerGb: 10.00,
    lastVerifiedDate: '2026-08-26',
    confidence: 'high'
  },
  {
    id: 'tnt-panalo-data-99',
    telco: 'TNT',
    name: 'Panalo Data 99',
    pricePhp: 99,
    dataAllowanceMb: 8 * 1024,
    validityDays: 7,
    isNoExpiry: false,
    freebieDetails: '8GB Open Data + Unli TikTok + Unli All-Net Calls/SMS for 7 Days',
    inclusions: 'Unli TikTok + Unli Calls/SMS',
    ussdCode: '*123#',
    smsKeyword: 'PANALO99',
    smsSendTo: '4545',
    category: 'popular',
    highlights: ['8GB Data', 'Unli TikTok + Allnet', '₱12.38 / GB'],
    costPerGb: 12.38,
    lastVerifiedDate: '2026-08-26',
    confidence: 'high'
  },
  {
    id: 'tnt-doble-giga-video-99',
    telco: 'TNT',
    name: 'Doble GIGA Video 99',
    pricePhp: 99,
    dataAllowanceMb: 16 * 1024,
    validityDays: 7,
    isNoExpiry: false,
    freebieDetails: '2GB Open Data + 2GB/day YouTube, Netflix, Prime Video (7 Days)',
    inclusions: '2GB/day Video Apps',
    ussdCode: '*123#',
    category: 'heavy_data',
    highlights: ['16GB Total Data', '2GB Daily Video', '₱6.19 / GB'],
    costPerGb: 6.19,
    lastVerifiedDate: '2026-08-26',
    confidence: 'medium'
  },
  {
    id: 'tnt-doble-giga-stories-99',
    telco: 'TNT',
    name: 'Doble GIGA Stories 99',
    pricePhp: 99,
    dataAllowanceMb: 16 * 1024,
    validityDays: 7,
    isNoExpiry: false,
    freebieDetails: '2GB Open Data + 2GB/day TikTok, Facebook, IG, Twitter (7 Days)',
    inclusions: '2GB/day Social Apps',
    ussdCode: '*123#',
    category: 'heavy_data',
    highlights: ['16GB Total Data', '2GB Daily Socials', '₱6.19 / GB'],
    costPerGb: 6.19,
    lastVerifiedDate: '2026-08-26',
    confidence: 'medium'
  },
  {
    id: 'tnt-tiktok-saya-50',
    telco: 'TNT',
    name: 'TikTok Saya 50',
    pricePhp: 50,
    dataAllowanceMb: 4 * 1024,
    validityDays: 3,
    isNoExpiry: false,
    freebieDetails: '1GB Open Data + 3GB TikTok + Unli All-Net SMS',
    inclusions: '3GB TikTok + Unli SMS',
    ussdCode: '*123#',
    category: 'budget',
    highlights: ['TikTok Fan Special', '4GB Total', '₱12.50 / GB'],
    costPerGb: 12.50,
    lastVerifiedDate: '2026-08-26',
    confidence: 'medium'
  },
  {
    id: 'tnt-sulit-affordaload-15',
    telco: 'TNT',
    name: 'Sulit Affordaload 15',
    pricePhp: 15,
    dataAllowanceMb: 500,
    validityDays: 2,
    isNoExpiry: false,
    freebieDetails: '500MB Open Access Data for 2 Days',
    inclusions: '500MB 2-Day Data',
    ussdCode: '*123#',
    smsKeyword: 'SULIT15',
    smsSendTo: '4545',
    category: 'budget',
    highlights: ['Micro Load Option', '₱15 Emergency Data', '₱30.00 / GB'],
    costPerGb: 30.00,
    lastVerifiedDate: '2026-08-26',
    confidence: 'high'
  },

  // ==========================================
  // --- TM (Touch Mobile - tmtambayan.ph) ---
  // ==========================================
  {
    id: 'tm-easysurf-50',
    telco: 'TM',
    name: 'EasySURF50',
    pricePhp: 50,
    dataAllowanceMb: 6 * 1024,
    validityDays: 3,
    isNoExpiry: false,
    freebieDetails: '3GB Open Access + 3GB (1GB/day) FunALIW (FB, YT, TikTok, MLBB) + Unli Allnet SMS',
    inclusions: '3GB FunALIW + Unli SMS',
    ussdCode: '*143#',
    smsKeyword: 'EZ50',
    smsSendTo: '8080',
    category: 'budget',
    highlights: ['Budget Pinoy Favorite', 'FunALIW apps', '₱8.33 / GB'],
    costPerGb: 8.33,
    lastVerifiedDate: '2026-08-26',
    confidence: 'high'
  },
  {
    id: 'tm-easysurf-75',
    telco: 'TM',
    name: 'EasySURF75',
    pricePhp: 75,
    dataAllowanceMb: 8 * 1024,
    validityDays: 3,
    isNoExpiry: false,
    freebieDetails: '2GB Open Access + 6GB (2GB/day) FunALIW + Unli Allnet Calls & SMS',
    inclusions: '6GB FunALIW + Unli Calls/SMS',
    ussdCode: '*143#',
    smsKeyword: 'EZ75',
    smsSendTo: '8080',
    category: 'popular',
    highlights: ['8GB Total Data', 'Unli Allnet Calls/SMS', '₱9.38 / GB'],
    costPerGb: 9.38,
    lastVerifiedDate: '2026-08-26',
    confidence: 'high'
  },
  {
    id: 'tm-easysurf-99',
    telco: 'TM',
    name: 'EasySURF99',
    pricePhp: 99,
    dataAllowanceMb: 17 * 1024,
    validityDays: 7,
    isNoExpiry: false,
    freebieDetails: '3GB Open Access + 14GB (2GB/day) FunALIW + Unli Allnet SMS',
    inclusions: '14GB FunALIW + Unli SMS',
    ussdCode: '*143#',
    smsKeyword: 'EZ99',
    smsSendTo: '8080',
    category: 'heavy_data',
    highlights: ['17GB Total Data', '2GB Daily FunALIW', '₱5.82 / GB'],
    costPerGb: 5.82,
    lastVerifiedDate: '2026-08-26',
    confidence: 'high'
  },
  {
    id: 'tm-easysurf-110',
    telco: 'TM',
    name: 'EasySURF110',
    pricePhp: 110,
    dataAllowanceMb: 18 * 1024,
    validityDays: 7,
    isNoExpiry: false,
    freebieDetails: '4GB Open Access + 14GB (2GB/day) FunALIW + Unli Allnet SMS',
    inclusions: '14GB FunALIW + Unli SMS',
    ussdCode: '*143#',
    smsKeyword: 'EZ110',
    smsSendTo: '8080',
    category: 'heavy_data',
    highlights: ['18GB Data', 'Unli Allnet SMS', '₱6.11 / GB'],
    costPerGb: 6.11,
    lastVerifiedDate: '2026-08-26',
    confidence: 'high'
  },
  {
    id: 'tm-easysurf-140',
    telco: 'TM',
    name: 'EasySURF140',
    pricePhp: 140,
    dataAllowanceMb: 18 * 1024,
    validityDays: 7,
    isNoExpiry: false,
    freebieDetails: '4GB Open Access + 14GB (2GB/day) FunALIW + Unli Allnet Calls & SMS',
    inclusions: '14GB FunALIW + Unli Calls/SMS',
    ussdCode: '*143#',
    smsKeyword: 'EZ140',
    smsSendTo: '8080',
    category: 'heavy_data',
    highlights: ['18GB Data', 'Unli Allnet Calls & SMS', '₱7.78 / GB'],
    costPerGb: 7.78,
    lastVerifiedDate: '2026-08-26',
    confidence: 'high'
  },
  {
    id: 'tm-easysurf-299',
    telco: 'TM',
    name: 'EasySURF299',
    pricePhp: 299,
    dataAllowanceMb: 40 * 1024,
    validityDays: 30,
    isNoExpiry: false,
    freebieDetails: '10GB Open Access + 30GB (1GB/day) FunALIW for 30 days',
    inclusions: '30GB FunALIW (30 Days)',
    ussdCode: '*143#',
    smsKeyword: 'EZ299',
    smsSendTo: '8080',
    category: 'heavy_data',
    highlights: ['40GB Monthly Data', '30 Days Peace of Mind', '₱7.48 / GB'],
    costPerGb: 7.48,
    lastVerifiedDate: '2026-08-26',
    confidence: 'high'
  },
  {
    id: 'tm-bigating-50',
    telco: 'TM',
    name: 'Big-Ating 50',
    pricePhp: 50,
    dataAllowanceMb: 5 * 1024,
    validityDays: 3,
    isNoExpiry: false,
    freebieDetails: '5GB All-Access Data + Unli All-Net Calls & SMS',
    inclusions: '5GB Open + Unli Calls/SMS',
    ussdCode: '*143#',
    smsKeyword: 'BIGATING50',
    smsSendTo: '8080',
    category: 'budget',
    highlights: ['5GB All-Access', 'Unli Allnet Calls & SMS', '₱10.00 / GB'],
    costPerGb: 10.00,
    lastVerifiedDate: '2026-08-26',
    confidence: 'high'
  },
  {
    id: 'tm-bigating-99',
    telco: 'TM',
    name: 'Big-Ating 99',
    pricePhp: 99,
    dataAllowanceMb: 10 * 1024,
    validityDays: 7,
    isNoExpiry: false,
    freebieDetails: '10GB All-Access Data + Unli Calls & SMS to all networks',
    inclusions: '10GB Open + Unli Calls/SMS',
    ussdCode: '*143#',
    smsKeyword: 'BIGATING99',
    smsSendTo: '8080',
    category: 'popular',
    highlights: ['10GB Big Data', 'Unli Allnet Call & Text', '₱9.90 / GB'],
    costPerGb: 9.90,
    lastVerifiedDate: '2026-08-26',
    confidence: 'high'
  },
  {
    id: 'tm-all-net-surf-10',
    telco: 'TM',
    name: 'ALL-NET SURF 10',
    pricePhp: 10,
    dataAllowanceMb: 200,
    validityDays: 1,
    isNoExpiry: false,
    freebieDetails: '100MB Open + 100MB FB/ML + 200 mins All-Net Calls + 200 SMS',
    inclusions: '200 mins calls + 200 SMS',
    ussdCode: '*143#',
    smsKeyword: 'ANS10',
    smsSendTo: '8080',
    category: 'budget',
    highlights: ['₱10 Micro Combo', '200 Mins Calls', '₱50.00 / GB'],
    costPerGb: 50.00,
    lastVerifiedDate: '2026-08-26',
    confidence: 'high'
  },
  {
    id: 'tm-all-net-surf-20',
    telco: 'TM',
    name: 'ALL-NET SURF 20',
    pricePhp: 20,
    dataAllowanceMb: 600,
    validityDays: 2,
    isNoExpiry: false,
    freebieDetails: '300MB Open + 150MB/day FunALIW + Unli Allnet Calls & SMS',
    inclusions: 'Unli Calls/SMS + FunALIW',
    ussdCode: '*143#',
    smsKeyword: 'ANS20',
    smsSendTo: '8080',
    category: 'budget',
    highlights: ['₱20 2-Day Combo', 'Unli Allnet Calls', '₱33.33 / GB'],
    costPerGb: 33.33,
    lastVerifiedDate: '2026-08-26',
    confidence: 'high'
  },
  {
    id: 'tm-all-net-surf-30',
    telco: 'TM',
    name: 'ALL-NET SURF 30',
    pricePhp: 30,
    dataAllowanceMb: 1200,
    validityDays: 3,
    isNoExpiry: false,
    freebieDetails: '750MB Open + 150MB/day FunALIW + Unli Allnet Calls & SMS',
    inclusions: 'Unli Calls/SMS + FunALIW',
    ussdCode: '*143#',
    smsKeyword: 'ANS30',
    smsSendTo: '8080',
    category: 'budget',
    highlights: ['1.2GB Total', 'Unli Allnet Calls/SMS', '₱25.00 / GB'],
    costPerGb: 25.00,
    lastVerifiedDate: '2026-08-26',
    confidence: 'high'
  },
  {
    id: 'tm-all-net-surf-70',
    telco: 'TM',
    name: 'ALL-NET SURF 70',
    pricePhp: 70,
    dataAllowanceMb: 2400,
    validityDays: 7,
    isNoExpiry: false,
    freebieDetails: '1GB Open + 200MB/day FunALIW + Unli Allnet Calls & SMS',
    inclusions: 'Unli Calls/SMS + FunALIW',
    ussdCode: '*143#',
    smsKeyword: 'ANS70',
    smsSendTo: '8080',
    category: 'popular',
    highlights: ['2.4GB Total', '7 Days Unli Calls/SMS', '₱29.17 / GB'],
    costPerGb: 29.17,
    lastVerifiedDate: '2026-08-26',
    confidence: 'high'
  },
  {
    id: 'tm-unli-call-text-150',
    telco: 'TM',
    name: 'TM Unli Call & Text 150',
    pricePhp: 150,
    dataAllowanceMb: 1024,
    validityDays: 15,
    isNoExpiry: false,
    freebieDetails: 'Unli Calls & SMS to all networks + 1GB Data for 15 Days',
    inclusions: '15 Days Unli Calls/SMS',
    ussdCode: '*143#',
    smsKeyword: 'UCT150',
    smsSendTo: '8080',
    category: 'popular',
    highlights: ['15-Day Unli Calls/SMS', '1GB Data', '₱150.00 / GB'],
    costPerGb: 150.00,
    lastVerifiedDate: '2026-08-26',
    confidence: 'high'
  },

  // ==========================================
  // --- DITO TELECOMMUNITY (dito.ph/prepaid) ---
  // ==========================================
  {
    id: 'dito-level-up-99-15d',
    telco: 'DITO',
    name: 'Level Up 99 (15D)',
    pricePhp: 99,
    dataAllowanceMb: 9 * 1024,
    validityDays: 15,
    isNoExpiry: false,
    freebieDetails: '9GB High-Speed Data + Unli DITO Calls + 300 mins all-net + Unli Allnet SMS',
    inclusions: '300 mins all-net + Unli SMS',
    ussdCode: '*185#',
    smsKeyword: 'LEVELUP99',
    smsSendTo: '185',
    category: 'popular',
    highlights: ['9GB for 15 Days', '300 mins allnet', '₱11.00 / GB'],
    costPerGb: 11.00,
    lastVerifiedDate: '2026-08-26',
    confidence: 'high'
  },
  {
    id: 'dito-level-up-99-30d',
    telco: 'DITO',
    name: 'Level Up 99 (30D)',
    pricePhp: 99,
    dataAllowanceMb: 7 * 1024,
    validityDays: 30,
    isNoExpiry: false,
    freebieDetails: '7GB High-Speed Data + Unli DITO Calls + 300 mins all-net + Unli Allnet SMS (30 Days)',
    inclusions: '30 Days Validity + 300 mins',
    ussdCode: '*185#',
    smsKeyword: 'LEVELUP99',
    smsSendTo: '185',
    category: 'popular',
    highlights: ['30 Days Validity for ₱99', '300 mins allnet', '₱14.14 / GB'],
    costPerGb: 14.14,
    lastVerifiedDate: '2026-08-26',
    confidence: 'medium'
  },
  {
    id: 'dito-level-up-199',
    telco: 'DITO',
    name: 'Level Up 199',
    pricePhp: 199,
    dataAllowanceMb: 16 * 1024,
    validityDays: 30,
    isNoExpiry: false,
    freebieDetails: '16GB High-Speed Data + Unli DITO Calls + 300 mins all-net + Prime Video Mobile',
    inclusions: 'Prime Video + 300 mins calls',
    ussdCode: '*185#',
    smsKeyword: 'LEVELUP199',
    smsSendTo: '185',
    category: 'popular',
    highlights: ['16GB Data for 1 Month', 'Prime Video included', '₱12.44 / GB'],
    costPerGb: 12.44,
    lastVerifiedDate: '2026-08-26',
    confidence: 'high'
  },
  {
    id: 'dito-level-up-299',
    telco: 'DITO',
    name: 'Level Up 299',
    pricePhp: 299,
    dataAllowanceMb: 28 * 1024,
    validityDays: 30,
    isNoExpiry: false,
    freebieDetails: '28GB High-Speed Data + 28GB 5G Bonus + Unli DITO Calls + 300 mins all-net + Prime Video',
    inclusions: '28GB 5G Bonus + Prime Video',
    ussdCode: '*185#',
    smsKeyword: 'LEVELUP299',
    smsSendTo: '185',
    category: 'heavy_data',
    highlights: ['28GB 4G + 28GB 5G', 'Prime Video', '₱10.68 / GB'],
    costPerGb: 10.68,
    lastVerifiedDate: '2026-08-26',
    confidence: 'high'
  },
  {
    id: 'dito-level-up-499',
    telco: 'DITO',
    name: 'Level Up 499',
    pricePhp: 499,
    dataAllowanceMb: 55 * 1024,
    validityDays: 30,
    isNoExpiry: false,
    freebieDetails: '55GB High-Speed Data + Unli DITO Calls + 300 mins all-net + Unli Allnet SMS + Prime Video',
    inclusions: '55GB + Prime Video',
    ussdCode: '*185#',
    smsKeyword: 'LEVELUP499',
    smsSendTo: '185',
    category: 'heavy_data',
    highlights: ['55GB Monthly Data', 'Prime Video Mobile', '₱9.07 / GB'],
    costPerGb: 9.07,
    lastVerifiedDate: '2026-08-26',
    confidence: 'high'
  },
  {
    id: 'dito-level-up-999',
    telco: 'DITO',
    name: 'Level Up 999',
    pricePhp: 999,
    dataAllowanceMb: 120 * 1024,
    validityDays: 30,
    isNoExpiry: false,
    freebieDetails: '120GB High-Speed Data + Unli DITO Calls + 300 mins all-net + Unli Allnet SMS + Prime Video',
    inclusions: '120GB + Prime Video',
    ussdCode: '*185#',
    smsKeyword: 'LEVELUP999',
    smsSendTo: '185',
    category: 'heavy_data',
    highlights: ['120GB Massive Data', 'Prime Video included', '₱8.33 / GB'],
    costPerGb: 8.33,
    lastVerifiedDate: '2026-08-26',
    confidence: 'high'
  },
  {
    id: 'dito-data-10',
    telco: 'DITO',
    name: 'DATA 10',
    pricePhp: 10,
    dataAllowanceMb: 1024,
    validityDays: 1,
    isNoExpiry: false,
    freebieDetails: '1GB High-Speed Data Sachet (Data only)',
    inclusions: '1GB 1-Day Data',
    ussdCode: '*185#',
    category: 'budget',
    highlights: ['₱10 Budget Sachet', '1GB Pure Data', '₱10.00 / GB'],
    costPerGb: 10.00,
    lastVerifiedDate: '2026-08-26',
    confidence: 'high'
  },
  {
    id: 'dito-data-20',
    telco: 'DITO',
    name: 'DATA 20',
    pricePhp: 20,
    dataAllowanceMb: 2048,
    validityDays: 3,
    isNoExpiry: false,
    freebieDetails: '2GB High-Speed Data Sachet (Data only)',
    inclusions: '2GB 3-Day Data',
    ussdCode: '*185#',
    category: 'budget',
    highlights: ['₱20 3-Day Sachet', '2GB Pure Data', '₱10.00 / GB'],
    costPerGb: 10.00,
    lastVerifiedDate: '2026-08-26',
    confidence: 'high'
  },
  {
    id: 'dito-data-50',
    telco: 'DITO',
    name: 'DATA 50',
    pricePhp: 50,
    dataAllowanceMb: 5120,
    validityDays: 7,
    isNoExpiry: false,
    freebieDetails: '5GB High-Speed Data Sachet (Data only)',
    inclusions: '5GB 7-Day Data',
    ussdCode: '*185#',
    category: 'budget',
    highlights: ['₱50 7-Day Sachet', '5GB Pure Data', '₱10.00 / GB'],
    costPerGb: 10.00,
    lastVerifiedDate: '2026-08-26',
    confidence: 'high'
  },
  {
    id: 'dito-unli-5g-299',
    telco: 'DITO',
    name: 'DITO UNLI 5G 299',
    pricePhp: 299,
    dataAllowanceMb: 999 * 1024,
    validityDays: 7,
    isNoExpiry: false,
    freebieDetails: 'Unli 5G Data + 10GB 4G Data + Unli DITO Calls + 300 mins all-net + Unli SMS (7 Days)',
    inclusions: 'Unli 5G + 10GB 4G Data',
    ussdCode: '*185#',
    smsKeyword: 'UNLI5G299',
    smsSendTo: '185',
    category: 'unli',
    highlights: ['Unli 5G Speed', '10GB 4G Backup', '< ₱0.30 / GB'],
    costPerGb: 0.30,
    lastVerifiedDate: '2026-08-26',
    confidence: 'high'
  },
  {
    id: 'dito-unli-5g-499',
    telco: 'DITO',
    name: 'DITO UNLI 5G 499',
    pricePhp: 499,
    dataAllowanceMb: 999 * 1024,
    validityDays: 15,
    isNoExpiry: false,
    freebieDetails: 'Unli 5G Data + 20GB 4G Data + Unli DITO Calls + 300 mins all-net + Unli SMS (15 Days)',
    inclusions: 'Unli 5G + 20GB 4G Data',
    ussdCode: '*185#',
    smsKeyword: 'UNLI5G499',
    smsSendTo: '185',
    category: 'unli',
    highlights: ['Unli 5G for 15 Days', '20GB 4G Backup', '< ₱0.50 / GB'],
    costPerGb: 0.50,
    lastVerifiedDate: '2026-08-26',
    confidence: 'high'
  },
  {
    id: 'dito-unli-5g-999',
    telco: 'DITO',
    name: 'DITO UNLI 5G 999',
    pricePhp: 999,
    dataAllowanceMb: 999 * 1024,
    validityDays: 30,
    isNoExpiry: false,
    freebieDetails: 'Unli 5G Data + 50GB 4G Data + Unli DITO Calls + 300 mins all-net + Unli SMS (30 Days)',
    inclusions: 'Unli 5G + 50GB 4G Data',
    ussdCode: '*185#',
    smsKeyword: 'UNLI5G999',
    smsSendTo: '185',
    category: 'unli',
    highlights: ['True Unli 5G Month', '50GB 4G backup', 'Ultra-fast'],
    costPerGb: 1.00,
    lastVerifiedDate: '2026-08-26',
    confidence: 'high'
  },
  {
    id: 'dito-advance-pay-713',
    telco: 'DITO',
    name: 'DITO Advance Pay 365D',
    pricePhp: 713,
    dataAllowanceMb: 96 * 1024,
    validityDays: 365,
    isNoExpiry: false,
    freebieDetails: '96GB data for 1 year (8GB/month auto-disbursed) + Unli DITO calls',
    inclusions: '1 Year Advance Pay (8GB/mo)',
    ussdCode: '*185#',
    smsKeyword: 'ADVANCE365',
    smsSendTo: '185',
    category: 'heavy_data',
    highlights: ['1 Full Year Peace of Mind', '₱7.43 / GB'],
    costPerGb: 7.43,
    lastVerifiedDate: '2026-08-26',
    confidence: 'high'
  },

  // ==========================================
  // --- GOMO (gomo.ph) ---
  // ==========================================
  {
    id: 'gomo-30gb-no-expiry',
    telco: 'GOMO',
    name: '30GB No Expiry',
    pricePhp: 399,
    dataAllowanceMb: 30 * 1024,
    validityDays: 0,
    isNoExpiry: true,
    freebieDetails: '30GB High Speed Data. Swap data to calls & SMS via Mo Creds on GOMO app.',
    inclusions: "'Mo Creds Swapping (No Expiry)",
    ussdCode: 'GOMO App',
    category: 'no_expiry',
    highlights: ["'Mo Creds Convertible", 'No Expiration', '₱13.30 / GB'],
    costPerGb: 13.30,
    lastVerifiedDate: '2026-08-26',
    confidence: 'high'
  },
  {
    id: 'gomo-55gb-no-expiry',
    telco: 'GOMO',
    name: '55GB No Expiry',
    pricePhp: 599,
    dataAllowanceMb: 55 * 1024,
    validityDays: 0,
    isNoExpiry: true,
    freebieDetails: '55GB High Speed Data with Mo Creds data swapping support',
    inclusions: "'Mo Creds Swapping (No Expiry)",
    ussdCode: 'GOMO App',
    category: 'no_expiry',
    highlights: ['Bulk No-Expiry Data', 'Lowest Cost No-Expiry', '₱10.89 / GB'],
    costPerGb: 10.89,
    lastVerifiedDate: '2026-08-26',
    confidence: 'high'
  },
  {
    id: 'gomo-100gb-no-expiry',
    telco: 'GOMO',
    name: '100GB No Expiry',
    pricePhp: 999,
    dataAllowanceMb: 100 * 1024,
    validityDays: 0,
    isNoExpiry: true,
    freebieDetails: '100GB Bulk High Speed Data with Mo Creds swapping support',
    inclusions: "'Mo Creds Swapping (No Expiry)",
    ussdCode: 'GOMO App',
    category: 'no_expiry',
    highlights: ['Max No-Expiry Pool', '100GB Data', '₱9.99 / GB'],
    costPerGb: 9.99,
    lastVerifiedDate: '2026-08-26',
    confidence: 'high'
  },
  {
    id: 'gomo-unli-data-30d',
    telco: 'GOMO',
    name: 'UNLI DATA 30 Days',
    pricePhp: 699,
    dataAllowanceMb: 999 * 1024,
    validityDays: 30,
    isNoExpiry: false,
    freebieDetails: 'Unli Data for 30 Days (Capped at 5Mbps speed - Flash Sale Promo)',
    inclusions: '30 Days Unli Data (5Mbps)',
    ussdCode: 'GOMO App',
    category: 'unli',
    highlights: ['Unlimited Browsing/Streaming', '30 Days', '< ₱0.70 / GB'],
    costPerGb: 0.70,
    lastVerifiedDate: '2026-08-26',
    confidence: 'high'
  }
];

/**
 * Recommend the best promo based on user burn rate and budget preference
 */
export function recommendPromos(burnRateGbPerDay: number, preferredTelco?: TelcoProvider | 'ALL' | string): {
  bestOverall: PromoItem;
  bestValue: PromoItem;
  bestNoExpiry: PromoItem;
  savingsInsight: string;
} {
  // If Sun is selected, map to Smart/TNT as Sun has been migrated into the Smart network
  const effectiveTelco = preferredTelco === 'Sun' ? 'Smart' : preferredTelco;

  const telcoFiltered = effectiveTelco && effectiveTelco !== 'ALL'
    ? PHILIPPINE_PROMOS.filter(p => p.telco.toLowerCase() === effectiveTelco.toLowerCase())
    : PHILIPPINE_PROMOS;

  const validPromos = telcoFiltered.length > 0 ? telcoFiltered : PHILIPPINE_PROMOS;

  // Best no-expiry
  const noExpiryPromos = validPromos.filter(p => p.isNoExpiry).sort((a, b) => a.costPerGb - b.costPerGb);
  const bestNoExpiry = noExpiryPromos[0] || PHILIPPINE_PROMOS.find(p => p.isNoExpiry)!;

  // Best value per GB
  const sortedByCost = [...validPromos].sort((a, b) => a.costPerGb - b.costPerGb);
  const bestValue = sortedByCost[0];

  // Best overall matched to user's daily burn rate (e.g. 7-day or 30-day needs)
  const estimatedWeeklyMb = burnRateGbPerDay * 7 * 1024;
  const bestOverall = validPromos.find(p => p.dataAllowanceMb >= estimatedWeeklyMb && p.validityDays >= 7)
    || validPromos.find(p => p.category === 'popular')
    || validPromos[0];

  const estimatedDaysLast = Math.round((bestOverall.dataAllowanceMb / (Math.max(0.1, burnRateGbPerDay) * 1024)) * 10) / 10;
  const savingsInsight = `At your rate of ${burnRateGbPerDay.toFixed(1)} GB/day, switching to ${bestOverall.name} gives you ~${estimatedDaysLast} days of coverage for just ₱${bestOverall.pricePhp}.`;

  return {
    bestOverall,
    bestValue,
    bestNoExpiry,
    savingsInsight
  };
}
